"""empty message

Revision ID: 336139dcf248
Revises: a2982dd4f431
Create Date: 2020-09-06 21:38:19.167642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336139dcf248'
down_revision = 'a2982dd4f431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###
