"""empty message

Revision ID: a2982dd4f431
Revises: c02e935b05a2
Create Date: 2020-08-30 21:35:49.237976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2982dd4f431'
down_revision = 'c02e935b05a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lottery_overview', sa.Column('graduating_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lottery_overview', 'graduating_year')
    # ### end Alembic commands ###
