"""empty message

Revision ID: a35e25787258
Revises: 03ac007a81c3
Create Date: 2020-08-24 18:05:22.078237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35e25787258'
down_revision = '03ac007a81c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('points_six', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'points_six')
    # ### end Alembic commands ###
