"""empty message

Revision ID: c02e935b05a2
Revises: ed2b6252983c
Create Date: 2020-08-29 20:12:04.159852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02e935b05a2'
down_revision = 'ed2b6252983c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('graduating_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'graduating_year')
    # ### end Alembic commands ###
