"""empty message

Revision ID: c4ea07e8b7ad
Revises: a35e25787258
Create Date: 2020-08-24 21:24:43.246024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ea07e8b7ad'
down_revision = 'a35e25787258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('num_submissions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'num_submissions')
    # ### end Alembic commands ###
