"""empty message

Revision ID: d1cab20eebd2
Revises: c4ea07e8b7ad
Create Date: 2020-08-27 16:32:21.535139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cab20eebd2'
down_revision = 'c4ea07e8b7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=1000), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=1000), nullable=True))
    op.add_column('user', sa.Column('organization', sa.String(length=1000), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('user', 'organization')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
